#!/usr/bin/python3.10

class Plant:  #this is a class, just a template. nothing in memory yet!
    def __init__(self, name, heigth):
        self.name = name
        self.heigth = heigth

    def grow(self):	#this is now a method. to modify the attributes of class
        self.heigth += 1
        print(f"{self.name} grew 1cm")









rose = Plant("rose", 20)
rose.grow()

print(f"{rose.name}, {rose.heigth}cm")
